### PR TITLE
[Docker] Connector runs on 3000 by default

### PR DESCRIPTION
**Pull request by lumberj**

### CODE REVIEW

**Comment by emschwartz** [comment]
What's the logic for changing it to 3000?

**Comment by lumberj** [comment]
> What's the logic for changing it to 3000?

The shared config module defaults to 3000
https://github.com/interledger/five-bells-shared/blob/master/lib/config.js#L83

If the operator wants to change the exposed port they can use 

```
CONNECTOR_PORT=5000 \
  docker run interledger/five-bells-connector \
  --expose $CONNECTOR_PORT \
  --env $CONNECTOR_PORT
```

**Comment by MatthewPhinney** [comment]
LGTM

**Comment by clark800** [comment]
Maybe we should have different default ports for the different components?

**Comment by lumberj** [comment]
@clark800  makes sense. Can followup in the future

**Pull request merged**
