### PR TITLE
Improved handshake with backend

### PR DESCRIPTION
**Pull request by gip**

### CODE REVIEW

**Comment by lumberj** [comment]
Can you add a test for this?

**Comment by gip** [comment]
Sure - though that will require a redesign of the way to handle configuration in the connector. So that will take some extra time.

**Comment by lumberj** [comment]
I think the investment to do that, as discussed in person, is worthwhile because it will reduce the probability of regressions and it is a much smaller investment in time today than it will be in a few months.

**Comment by gip** [comment]
I totally agree, I was just updating the ticket to capture our discussion :)

**Comment by lumberj** [comment]
LGTM -- discussed offline, will followup with unit tests to unblock integration testing for now

**Pull request merged**
