### PR TITLE
[FEATURE] Enable CORS

### PR DESCRIPTION
**Pull request by emschwartz**
Ledger [allows CORS](https://github.com/interledger/five-bells-ledger/blob/master/src/lib/app.js#L38) but the connector does not

### CODE REVIEW

**Comment by lumberj** [comment]
Why is this necessary?

**Comment by emschwartz** [comment]
If the sender is used within the browser it needs to be able to communicate with the connectors to ask for quotes

**Comment by lumberj** [comment]
LGTM

**Comment by clark800** [comment]
> If the sender is used within the browser it needs to be able to communicate with the connectors to ask for quotes

This knowledge will probably get lost in the PR comments; might be a good thing to put in a code comment.

**Pull request merged**
