### PR TITLE
Fix exception on payment that is missing the execution_condition

### PR DESCRIPTION
**Pull request by clark800**
Addresses RILP-362. I'm not sure how to test this now since the payments endpoint was removed.

### CODE REVIEW

**Comment by lumberj** [comment]
@clark800 looks like all the tests for these conditions are in https://github.com/interledger/five-bells-connector/blob/master/test/notificationSpec.js

**Comment by emschwartz** [comment]
This fix is technically correct because it's in the function `sourceConditionIsDestinationTransfer`. However, we should actually allow payments where the source transfer has no execution condition (irrespective of whether or not the destination transfer does). That should be handled as a separate check though

**Comment by lumberj** [comment]
@clark800 is this already covered by one of the test cases in notificationSpec? Otherwise LGTM

**Comment by clark800** [comment]
This isn't covered because the tests pass with or without this change. It is not clear to me how to add a test case.

**Comment by lumberj** [comment]
@clark800 you can modify this test case, and write a failing test. https://github.com/interledger/five-bells-connector/blob/master/test/notificationSpec.js#L199 -- the connector receives a notification with a payment in the memo missing an execution condition.

**Comment by clark800** [comment]
@lumberj updated

**Comment by lumberj** [comment]
LGTM

**Pull request merged**
